### ISSUE TITLE
Error (use-package): Unrecognized keyword: :blackout

### ISSUE THREAD

**Issue by doolio** [raxod502/blackout#2]
The full warning message is as follows:
```
Error (use-package): Failed to parse package org-agenda: use-package: Unrecognized keyword: :blackout
```

I've installed both `use-package`, `org` and `blackout` with `straight`. These are the installed versions:

```
 ("blackout" . "4bac44671fca4c98d96aa94c79946bf4d4baf0ee")
 ("org" . "b6e3e8f2b692ed1720751611d41d53765743bea6")
 ("use-package" . "42db6b3d90ee57d0f5947d3b0bf4b0010bdf7b40")
```

Now I configure `org-agenda` as follows stealing your `use-feature` macro from `radian` :) 

```
(use-feature org-agenda                 ; Task management
  :bind (("C-c o a" . org-agenda)
         ("H-a"     . hydra-org-agenda/body))
  :blackout "Org-Agenda")
```

However, per the error message it seems the `:blackout` keyword is not recognised by `use-package` mhich would contradict the README. My aim is to only see "Org-Agenda" as the mode lighter. I was hoping `blackout` would succeed where previously `diminish` and `delight` failed for me.

Thanks for your time.

**Comment by raxod502** [comment]
Let me know if the latest commit fixes it for you.

**Comment by doolio** [comment]
Yes, with this fix I no longer see the error message. Thank you.

I should have stated (and/or realised) that I had deferred the loading of `blackout` before but I guess you figured that was the case with this fix.

Now, I still see the additional mode lighters when I make any changes to the agenda view (e.g. "Org-Agenda Day Ddl Grid Habit") but they disappear when I rebuild (`r`) the view and I then only see the desired "Org-Agenda". Is it too much to ask of `blackout` to avoid seeing even these transient lighters? Either way `blackout` achieves what the other packages did not so I'm happy. Thanks again for your time. Please feel free to close this issue.

**Comment by raxod502** [comment]
That's a reasonable feature request. Why don't you open a new issue with directions to reproduce the problem?
