### ISSUE TITLE
Improvements for comparison documentation

### ISSUE THREAD

**Issue by phil-s** [raxod502/blackout#3]
FWIW some of the `delight` examples for `use-package` are unnecessarily verbose.

In particular, the library name shouldn't ever be needed for minor modes, because that is already implicit when `use-package` is being used (for major modes you would still want to pass the `:major` argument).  You can simplify these examples further still, though:

To hide a lighter:

```el
(use-package rainbow-mode
  :delight)
```

To rename a lighter:

```el
(use-package rainbow-mode
  :delight " Bar")
```

These expand to `(delight '((rainbow-mode nil rainbow-mode)))` and `(delight '((rainbow-mode " Bar" rainbow-mode)))` respectively.

You only need to pass the mode name if that did *not* match the package/feature name.

Your final example is also passing in too many arguments -- I think you've accidentally kept the `nil` when adding the `" Foo"`:

```el
(use-package quux
  :delight
  (foo-mode " Foo" nil "quux")
  (bar-mode " Bar" nil "quux"))
```

That should be:

```el
(use-package quux
  :delight
  (foo-mode " Foo")
  (bar-mode " Bar"))
```

**Comment by phil-s** [comment]
These should be the correct equivalents:

```el

;; auto-fill-mode (standard minor mode)
(blackout 'auto-fill-mode)
(delight 'auto-fill-function nil t)

(blackout 'auto-fill-mode " Auto-Fill")
(delight 'auto-fill-function " Auto-Fill" t)

;; emacs-lisp-mode (major mode)
(blackout 'emacs-lisp-mode "Elisp")
(delight 'emacs-lisp-mode "Elisp" :major)

;; ivy-mode in ivy.el
(with-eval-after-load 'ivy
  (blackout 'ivy-mode))
(delight 'ivy-mode nil "ivy")

;; foo-mode in foo-mode.el
(use-package foo-mode
  :blackout t)
(use-package foo-mode
  :delight)

(use-package foo-mode
  :blackout " Foo")
(use-package foo-mode
  :delight " Foo")

;; foo-mode in foo.el
(use-package foo
  :blackout t)
(use-package foo
  :delight foo-mode)

(use-package foo
  :blackout " Foo")
(use-package foo
  :delight foo-mode " Foo")

;; foo-mode and bar-mode in quux.el
(use-package quux
  :blackout ((foo-mode . " Foo")
             (bar-mode . " Bar")))
(use-package quux
  :delight (foo-mode " Foo")
           (bar-mode " Bar"))
```

**Comment by raxod502** [comment]
Thanks for the corrections, would you mind submitting a pull request fixing the README?

**Comment by raxod502** [comment]
Merged, thanks for taking the time!
